sudo: required

language: c

os:
  - linux

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before_script:
  - /usr/bin/cc -v

script:
  - cd ref
  - make test/test_dilithium CFLAGS="-fprofile-arcs -ftest-coverage -g -Wall -Wextra -O0 -fomit-frame-pointer -march=native -fPIC"
  - ./test/test_dilithium

after_success:
  - lcov -d . --capture --output-file coverage.info
  - coveralls-lcov coverage.info
